/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/**/*.{js,ts,jsx,tsx}",
    "./app/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        'bapi-blue-50': 'var(--color-primary-50)',
        'bapi-blue-100': 'var(--color-primary-100)',
        'bapi-blue-200': 'var(--color-primary-200)',
        'bapi-blue-300': 'var(--color-primary-300)',
        'bapi-blue-400': 'var(--color-primary-400)',
        'bapi-blue-500': 'var(--color-primary-500)',
        'bapi-blue-600': 'var(--color-primary-600)',
        'bapi-blue-700': 'var(--color-primary-700)',
        'bapi-blue-800': 'var(--color-primary-800)',
        'bapi-blue-900': 'var(--color-primary-900)',
        'bapi-blue-950': 'var(--color-primary-950)',
        'bapi-accent': 'var(--color-accent-500)',
        'bapi-accent-100': 'var(--color-accent-100)',
        'bapi-accent-200': 'var(--color-accent-200)',
        'bapi-accent-300': 'var(--color-accent-300)',
        'bapi-accent-400': 'var(--color-accent-400)',
        'bapi-accent-500': 'var(--color-accent-500)',
        'bapi-accent-600': 'var(--color-accent-600)',
        'bapi-accent-700': 'var(--color-accent-700)',
        'bapi-accent-800': 'var(--color-accent-800)',
        'bapi-accent-900': 'var(--color-accent-900)',
        'bapi-gray-100': 'var(--color-neutral-100)',
        'bapi-gray-200': 'var(--color-neutral-200)',
        'bapi-gray-300': 'var(--color-neutral-300)',
        'bapi-gray-400': 'var(--color-neutral-400)',
        'bapi-gray-500': 'var(--color-neutral-500)',
        'bapi-gray-600': 'var(--color-neutral-600)',
        'bapi-gray-700': 'var(--color-neutral-700)',
        'bapi-gray-800': 'var(--color-neutral-800)',
        'bapi-gray-900': 'var(--color-neutral-900)',
      },
    },
  },
  plugins: [],
};
